server:
  port: 8082
  servlet:
    session:
      cookie:
        secure: false

spring:
  autoconfigure:
    exclude: org.springframework.boot.session.data.redis.autoconfigure.SessionDataRedisAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: local-client-id
            client-secret: local-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

auth:
  cookie:
    secure: false

feign:
  client:
    gateway:
      url: http://localhost:8080
