apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: front-config